name: Deploy WordPress Theme & Plugins

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------
      # Setup PHP for Composer
      # ---------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Install PHP dependencies (Composer)
        run: composer install --no-dev --optimize-autoloader

      # ---------------------------
      # Cache Theme Vendor folder
      # ---------------------------
      - name: Cache Theme Composer
        uses: actions/cache@v4
        with:
          path: wp-content/themes/itschrisdinh/vendor
          key: sage-composer-${{ hashFiles('wp-content/themes/itschrisdinh/composer.lock') }}

      # ---------------------------
      # Install Theme Composer (Sage)
      # ---------------------------
      - name: Install Theme Composer Dependencies
        working-directory: wp-content/themes/itschrisdinh
        run: composer install --no-dev --optimize-autoloader

      # ---------------------------
      # Setup Node for Theme Build
      # ---------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install theme dependencies
        working-directory: wp-content/themes/itschrisdinh
        run: yarn install --frozen-lockfile

      - name: Build theme
        working-directory: wp-content/themes/itschrisdinh
        run: yarn build

      # ---------------------------
      # Deploy Plugins via SFTP
      # ---------------------------
      - name: Deploy Plugins via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "wp-content/plugins/*"
          target: "${{ secrets.SFTP_ROOT }}/wp-content/plugins/"
          strip_components: 0

      # ---------------------------
      # Deploy Theme via SFTP
      # ---------------------------
      - name: Deploy Theme via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "wp-content/themes/itschrisdinh/*"
          target: "${{ secrets.SFTP_ROOT }}/wp-content/themes/itschrisdinh/"
          strip_components: 0
          recursive: true
          exclude: |
            **/node_modules/**
            **/.git/**
            **/.github/**
            **/src/**
            **/*.map
